apiVersion: apps/v1
kind: Deployment
metadata:
  name: infos-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infos
  template:
    metadata:
      labels:
        app: infos
    spec:
      containers:
        - name: infos
          image: naoufalbelhour/skeleton-infos
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: skeleton
            - name: MONGO_URI
              value: 'mongodb://infos-mongo-srv:27017/infos'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: infos-srv
spec:
  selector:
    app: infos
  ports:
    - name: infos
      protocol: TCP
      port: 3000
      targetPort: 3000
