name: tests-infos

on:
  pull_request:
    paths:
      - 'infos/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd infos && npm install && npm run test:ci
